version: '3'
services:
  a-prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: a-mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  a-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - a-mysql:/var/lib/mysql
volumes:
  a-mysql:
